# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Access < Formula
  desc ""
  homepage "https://indent.com"
  version "0.10.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/indentapis/homebrew-access/releases/download/v0.10.3/access_0.10.3_darwin_amd64.zip"
      sha256 "485be389d935d9957b6630347ca53dd5f00e7b7ab0ef829d12ed0d7f0f053343"

      def install
        bin.install "access_v0.10.3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/indentapis/homebrew-access/releases/download/v0.10.3/access_0.10.3_darwin_arm64.zip"
      sha256 "2eb5a86b07bc6f922ebd31aafed8cc12f6a33b8f66d425c655ff2ff516b14c80"

      def install
        bin.install "access_v0.10.3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/indentapis/homebrew-access/releases/download/v0.10.3/access_0.10.3_linux_arm64.zip"
      sha256 "5b1bfeec437c58c5d867b9e5ef49b8a99dcdce841944dd6d39df8cb2e4439f67"

      def install
        bin.install "access_v0.10.3"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/indentapis/homebrew-access/releases/download/v0.10.3/access_0.10.3_linux_amd64.zip"
      sha256 "7cccb3dcead8da22a76f55e62655ea3f35bdd91886b39aef8d596a48a8ddfee6"

      def install
        bin.install "access_v0.10.3"
      end
    end
  end
end
