# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Access < Formula
  desc ""
  homepage "https://indent.com"
  version "0.10.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/indentapis/access/releases/download/v0.10.5/access_0.10.5_darwin_amd64.zip"
      sha256 "d3fc8ea5f0ea4402ec4548e6c50ee6b3dda6fbece17795bc68d1c82db0e15f58"

      def install
        bin.install "access_v0.10.5"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/indentapis/access/releases/download/v0.10.5/access_0.10.5_darwin_arm64.zip"
      sha256 "e94e16c8a38978a70364932b2b12d04f50946b19fd46d7184f668ad87a3db36e"

      def install
        bin.install "access_v0.10.5"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/indentapis/access/releases/download/v0.10.5/access_0.10.5_linux_arm64.zip"
      sha256 "81b92b7cdbe144c57badae16bb40d48dba22cd9876e7d8ad36ca0a0337efdba7"

      def install
        bin.install "access_v0.10.5"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/indentapis/access/releases/download/v0.10.5/access_0.10.5_linux_amd64.zip"
      sha256 "2feff8133d0c6413765831c8eff98091bf5d3aa6a8e4c080db1ffe7f71cf3fb3"

      def install
        bin.install "access_v0.10.5"
      end
    end
  end
end
