# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Access < Formula
  desc ""
  homepage "https://indent.com"
  version "0.10.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/indentapis/homebrew-access/releases/download/v0.10.4/access_0.10.4_darwin_arm64.zip"
      sha256 "32270cd0d15b34f1d3ed560b6e974d41f7c57f4f3860b7fbe4364b61af163119"

      def install
        bin.install "access_v0.10.4"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/indentapis/homebrew-access/releases/download/v0.10.4/access_0.10.4_darwin_amd64.zip"
      sha256 "77acd1ae9dd64f6cfd42129714b148f7773059103ab3663ff6dbe97ac7b0abe9"

      def install
        bin.install "access_v0.10.4"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/indentapis/homebrew-access/releases/download/v0.10.4/access_0.10.4_linux_arm64.zip"
      sha256 "1c1662bef5b72f79e846c281691aa5c47edee87387ad38461d127597161c6ead"

      def install
        bin.install "access_v0.10.4"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/indentapis/homebrew-access/releases/download/v0.10.4/access_0.10.4_linux_amd64.zip"
      sha256 "520aa4f20b5658a58eb78d40b791c063f0f6c096d82b9e33dc5c8dcd9fbe72ef"

      def install
        bin.install "access_v0.10.4"
      end
    end
  end
end
